# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'U:/extensions/studioTools/python/arxLoader/ui.ui'
#
# Created: Sun Dec 28 23:34:07 2014
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_loaderWindow(object):
    def setupUi(self, loaderWindow):
        loaderWindow.setObjectName("loaderWindow")
        loaderWindow.resize(874, 682)
        self.centralwidget = QtGui.QWidget(loaderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 851, 641))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.projectInfo_frame = QtGui.QFrame(self.frame)
        self.projectInfo_frame.setGeometry(QtCore.QRect(310, 80, 231, 101))
        self.projectInfo_frame.setFrameShape(QtGui.QFrame.Box)
        self.projectInfo_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.projectInfo_frame.setObjectName("projectInfo_frame")
        self.gridLayout = QtGui.QGridLayout(self.projectInfo_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.projectInfo_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.shot_label = QtGui.QLabel(self.projectInfo_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.shot_label.setFont(font)
        self.shot_label.setObjectName("shot_label")
        self.gridLayout.addWidget(self.shot_label, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.projectInfo_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.episode_label = QtGui.QLabel(self.projectInfo_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.episode_label.setFont(font)
        self.episode_label.setObjectName("episode_label")
        self.gridLayout.addWidget(self.episode_label, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.projectInfo_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.sequence_label = QtGui.QLabel(self.projectInfo_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.sequence_label.setFont(font)
        self.sequence_label.setObjectName("sequence_label")
        self.gridLayout.addWidget(self.sequence_label, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.projectInfo_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.step_label = QtGui.QLabel(self.projectInfo_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.step_label.setFont(font)
        self.step_label.setObjectName("step_label")
        self.gridLayout.addWidget(self.step_label, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 291, 37))
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shotgun_radioButton = QtGui.QRadioButton(self.frame_3)
        self.shotgun_radioButton.setChecked(True)
        self.shotgun_radioButton.setObjectName("shotgun_radioButton")
        self.horizontalLayout.addWidget(self.shotgun_radioButton)
        self.manualBrowser_radioButton = QtGui.QRadioButton(self.frame_3)
        self.manualBrowser_radioButton.setObjectName("manualBrowser_radioButton")
        self.horizontalLayout.addWidget(self.manualBrowser_radioButton)
        self.filter_frame = QtGui.QFrame(self.frame)
        self.filter_frame.setGeometry(QtCore.QRect(310, 520, 231, 111))
        self.filter_frame.setFrameShape(QtGui.QFrame.Box)
        self.filter_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.filter_frame.setObjectName("filter_frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.filter_frame)
        self.gridLayout_2.setHorizontalSpacing(11)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.parent_comboBox = QtGui.QComboBox(self.filter_frame)
        self.parent_comboBox.setEnabled(False)
        self.parent_comboBox.setObjectName("parent_comboBox")
        self.gridLayout_2.addWidget(self.parent_comboBox, 2, 0, 1, 1)
        self.variation_checkBox = QtGui.QCheckBox(self.filter_frame)
        self.variation_checkBox.setObjectName("variation_checkBox")
        self.gridLayout_2.addWidget(self.variation_checkBox, 3, 1, 1, 1)
        self.variation_comboBox = QtGui.QComboBox(self.filter_frame)
        self.variation_comboBox.setEnabled(False)
        self.variation_comboBox.setObjectName("variation_comboBox")
        self.gridLayout_2.addWidget(self.variation_comboBox, 3, 0, 1, 1)
        self.type_checkBox = QtGui.QCheckBox(self.filter_frame)
        self.type_checkBox.setObjectName("type_checkBox")
        self.gridLayout_2.addWidget(self.type_checkBox, 1, 1, 1, 1)
        self.type_comboBox = QtGui.QComboBox(self.filter_frame)
        self.type_comboBox.setEnabled(False)
        self.type_comboBox.setObjectName("type_comboBox")
        self.gridLayout_2.addWidget(self.type_comboBox, 1, 0, 1, 1)
        self.parent_checkBox = QtGui.QCheckBox(self.filter_frame)
        self.parent_checkBox.setObjectName("parent_checkBox")
        self.gridLayout_2.addWidget(self.parent_checkBox, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.filter_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 4)
        self.gridLayout_2.setColumnStretch(1, 3)
        self.search_frame = QtGui.QFrame(self.frame)
        self.search_frame.setGeometry(QtCore.QRect(310, 470, 231, 40))
        self.search_frame.setFrameShape(QtGui.QFrame.Box)
        self.search_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.search_frame.setObjectName("search_frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.search_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtGui.QLabel(self.search_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.search_lineEdit = QtGui.QLineEdit(self.search_frame)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.horizontalLayout_2.addWidget(self.search_lineEdit)
        self.add_pushButton = QtGui.QPushButton(self.frame)
        self.add_pushButton.setGeometry(QtCore.QRect(350, 350, 61, 31))
        self.add_pushButton.setObjectName("add_pushButton")
        self.remove_pushButton = QtGui.QPushButton(self.frame)
        self.remove_pushButton.setGeometry(QtCore.QRect(440, 350, 61, 31))
        self.remove_pushButton.setObjectName("remove_pushButton")
        self.inforamtion_frame = QtGui.QFrame(self.frame)
        self.inforamtion_frame.setGeometry(QtCore.QRect(310, 190, 231, 131))
        self.inforamtion_frame.setFrameShape(QtGui.QFrame.Box)
        self.inforamtion_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.inforamtion_frame.setObjectName("inforamtion_frame")
        self.label_15 = QtGui.QLabel(self.inforamtion_frame)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.information_label = QtGui.QLabel(self.inforamtion_frame)
        self.information_label.setGeometry(QtCore.QRect(10, 30, 211, 91))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.information_label.setFont(font)
        self.information_label.setObjectName("information_label")
        self.clear_pushButton = QtGui.QPushButton(self.frame)
        self.clear_pushButton.setGeometry(QtCore.QRect(400, 390, 61, 20))
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 80, 291, 551))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.main_label = QtGui.QLabel(self.frame_2)
        self.main_label.setGeometry(QtCore.QRect(10, 10, 105, 13))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.main_label.setFont(font)
        self.main_label.setObjectName("main_label")
        self.main_listWidget = QtGui.QListWidget(self.frame_2)
        self.main_listWidget.setGeometry(QtCore.QRect(10, 30, 271, 451))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.main_listWidget.setFont(font)
        self.main_listWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.main_listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.main_listWidget.setObjectName("main_listWidget")
        self.createReference_pushButton = QtGui.QPushButton(self.frame_2)
        self.createReference_pushButton.setGeometry(QtCore.QRect(10, 510, 271, 31))
        self.createReference_pushButton.setObjectName("createReference_pushButton")
        self.thumbnail_checkBox = QtGui.QCheckBox(self.frame_2)
        self.thumbnail_checkBox.setGeometry(QtCore.QRect(10, 490, 101, 17))
        self.thumbnail_checkBox.setChecked(True)
        self.thumbnail_checkBox.setObjectName("thumbnail_checkBox")
        self.selectedReference_checkBox = QtGui.QCheckBox(self.frame_2)
        self.selectedReference_checkBox.setGeometry(QtCore.QRect(130, 490, 151, 17))
        self.selectedReference_checkBox.setChecked(False)
        self.selectedReference_checkBox.setObjectName("selectedReference_checkBox")
        self.list_frame = QtGui.QFrame(self.frame)
        self.list_frame.setGeometry(QtCore.QRect(550, 80, 291, 551))
        self.list_frame.setFrameShape(QtGui.QFrame.Box)
        self.list_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.list_frame.setObjectName("list_frame")
        self.createAllReference_pushButton = QtGui.QPushButton(self.list_frame)
        self.createAllReference_pushButton.setGeometry(QtCore.QRect(10, 510, 271, 31))
        self.createAllReference_pushButton.setObjectName("createAllReference_pushButton")
        self.list_listWidget = QtGui.QListWidget(self.list_frame)
        self.list_listWidget.setGeometry(QtCore.QRect(10, 30, 271, 431))
        self.list_listWidget.setObjectName("list_listWidget")
        self.createSelectedReference_pushButton = QtGui.QPushButton(self.list_frame)
        self.createSelectedReference_pushButton.setGeometry(QtCore.QRect(10, 470, 271, 31))
        self.createSelectedReference_pushButton.setObjectName("createSelectedReference_pushButton")
        self.referenceList_label = QtGui.QLabel(self.list_frame)
        self.referenceList_label.setGeometry(QtCore.QRect(10, 10, 105, 13))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.referenceList_label.setFont(font)
        self.referenceList_label.setObjectName("referenceList_label")
        self.logo_label = QtGui.QLabel(self.frame)
        self.logo_label.setGeometry(QtCore.QRect(320, 10, 221, 61))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.logo_label.setFont(font)
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        loaderWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(loaderWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 21))
        self.menubar.setObjectName("menubar")
        loaderWindow.setMenuBar(self.menubar)

        self.retranslateUi(loaderWindow)
        QtCore.QObject.connect(self.type_checkBox, QtCore.SIGNAL("toggled(bool)"), self.type_comboBox.setEnabled)
        QtCore.QObject.connect(self.parent_checkBox, QtCore.SIGNAL("toggled(bool)"), self.parent_comboBox.setEnabled)
        QtCore.QObject.connect(self.variation_checkBox, QtCore.SIGNAL("toggled(bool)"), self.variation_comboBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(loaderWindow)

    def retranslateUi(self, loaderWindow):
        loaderWindow.setWindowTitle(QtGui.QApplication.translate("loaderWindow", "Arx Anim Loader v.1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("loaderWindow", "Sequence : ", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_label.setText(QtGui.QApplication.translate("loaderWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("loaderWindow", "Shot : ", None, QtGui.QApplication.UnicodeUTF8))
        self.episode_label.setText(QtGui.QApplication.translate("loaderWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("loaderWindow", "Episode : ", None, QtGui.QApplication.UnicodeUTF8))
        self.sequence_label.setText(QtGui.QApplication.translate("loaderWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("loaderWindow", "Step : ", None, QtGui.QApplication.UnicodeUTF8))
        self.step_label.setText(QtGui.QApplication.translate("loaderWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.shotgun_radioButton.setText(QtGui.QApplication.translate("loaderWindow", "Shotgun shot assets", None, QtGui.QApplication.UnicodeUTF8))
        self.manualBrowser_radioButton.setText(QtGui.QApplication.translate("loaderWindow", "Manual Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.variation_checkBox.setText(QtGui.QApplication.translate("loaderWindow", "Variation", None, QtGui.QApplication.UnicodeUTF8))
        self.type_checkBox.setText(QtGui.QApplication.translate("loaderWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.parent_checkBox.setText(QtGui.QApplication.translate("loaderWindow", "Parent", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("loaderWindow", "Asset filters : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("loaderWindow", "Search : ", None, QtGui.QApplication.UnicodeUTF8))
        self.add_pushButton.setText(QtGui.QApplication.translate("loaderWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_pushButton.setText(QtGui.QApplication.translate("loaderWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("loaderWindow", "Information : ", None, QtGui.QApplication.UnicodeUTF8))
        self.information_label.setText(QtGui.QApplication.translate("loaderWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_pushButton.setText(QtGui.QApplication.translate("loaderWindow", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.main_label.setText(QtGui.QApplication.translate("loaderWindow", "Shotgun Asset List", None, QtGui.QApplication.UnicodeUTF8))
        self.main_listWidget.setSortingEnabled(False)
        self.createReference_pushButton.setText(QtGui.QApplication.translate("loaderWindow", "Create All Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbnail_checkBox.setText(QtGui.QApplication.translate("loaderWindow", "Show Thumbnail", None, QtGui.QApplication.UnicodeUTF8))
        self.selectedReference_checkBox.setText(QtGui.QApplication.translate("loaderWindow", "Create selected only", None, QtGui.QApplication.UnicodeUTF8))
        self.createAllReference_pushButton.setText(QtGui.QApplication.translate("loaderWindow", "Create All References", None, QtGui.QApplication.UnicodeUTF8))
        self.createSelectedReference_pushButton.setText(QtGui.QApplication.translate("loaderWindow", "Create Selected Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.referenceList_label.setText(QtGui.QApplication.translate("loaderWindow", "Reference lists", None, QtGui.QApplication.UnicodeUTF8))

